# When looking at this point in Gimp, you must switch X and Y
tag1X: 73
tag1Y: 62

tag2X: 57
tag2Y: 35

tag3X: 116
tag3Y: 84

tag4X: 44
tag4Y: 56

tag5X: 98
tag5Y: 54

tag6X: 97
tag6Y: 60

tag7X: 124
tag7Y: 46

tag8X: 127
tag8Y: 56

tag9X: 126
tag9Y: 63

tag10X: 149
tag10Y: 75