# When looking at this point in Gimp, you must switch X and Y
tag1X: 115
tag1Y: 85

tag2X: 112
tag2Y: 44

tag3X: 93
tag3Y: 40

tag4X: 66
tag4Y: 36

tag5X: 43
tag5Y: 40

tag6X: 48
tag6Y: 58

tag7X: 98
tag7Y: 55

tag8X: 106
tag8Y: 72

tag9X: 116
tag9Y: 84

tag10X: 152
tag10Y: 91