mapPath: ./../Images/inb3123_small.pgm
resolution: 1
imgResolution: 1
initX: 97
initY: 102
initOrientation: 180
initFov: 180
initRange: 6
precision: 1
threshold: 0
RFIDfreq: 865e6
txtPower: 0
w_infoGain: 1
w_travelDistance: 0
w_sensingTime: 0
w_rfidGain: 0
# outLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv
# coverageLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_0_1.csv
# detectionLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv
# accuracyLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv


# When looking at this point in Gimp, you must switch X and Y
tag1X: 161
tag1Y: 33

tag2X: 148
tag2Y: 47

tag3X: 139
tag3Y: 56

tag4X: 109
tag4Y: 51

tag5X: 123
tag5Y: 66

tag6X: 115
tag6Y: 78

tag7X: 108
tag7Y: 86

tag8X: 99
tag8Y: 96

tag9X: 91
tag9Y: 87

tag10X: 86
tag10Y: 80