# When looking at this point in Gimp, you must switch X and Y
tag1X: 137
tag1Y: 73

tag2X: 150
tag2Y: 89

tag3X: 113
tag3Y: 78

tag4X: 108
tag4Y: 54

tag5X: 98
tag5Y: 54

tag6X: 90
tag6Y: 39

tag7X: 84
tag7Y: 65

tag8X: 62
tag8Y: 60

tag9X: 45
tag9Y: 32

tag10X: 40
tag10Y: 56