mapPath: ./../Images/inb3123_small.pgm
resolution: 1
imgResolution: 1
initX: 97
initY: 102
initOrientation: 180
initFov: 180
initRange: 6
precision: 1
threshold: 0
RFIDfreq: 865e6
txtPower: 0
w_infoGain: 1
w_travelDistance: 0
w_sensingTime: 0
w_rfidGain: 0
# outLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_result_inb3123_1.csv
# coverageLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_coverage_mcdm_inb3123_0_1.csv
# detectionLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/distance_tag_25r.csv
# accuracyLog: /home/pulver/Dropbox/University/PostDoc/MCDM/mcdm/logic_exps/mcdm_vs_avg/inb3123/mcdm_ccuracy_25r.csv


# When looking at this point in Gimp, you must switch X and Y
tag1X: 163
tag1Y: 31

tag2X: 160
tag2Y: 35

tag3X: 157
tag3Y: 41

tag4X: 144
tag4Y: 47

tag5X: 140
tag5Y: 58

tag6X: 126
tag6Y: 63

tag7X: 118
tag7Y: 64

tag8X: 118
tag8Y: 79

tag9X: 109
tag9Y: 84

tag10X: 96
tag10Y: 91